### ISSUE TITLE
(bug) Game view black bars should go away when mouse stops moving

### ISSUE THREAD

**Issue by bcbcb** [orange-quicksand/orange-quicksand#80]

**Comment by bcbcb** [comment]
Also I think the user should still be able to control the game even when the bars are showing.

**Comment by omarduarte** [comment]
This still happening after the latest PR?

**Comment by omarduarte** [comment]
I am testing it right now. The black bars only stick when the mouse is hovering a menu item. The black bars then go away 2.5 seconds after the mouse stops moving. I'm able to play the game even when the black bar appears.

**Comment by bcbcb** [comment]
This is fixed now, nice job.
